services:
  - type: web
    name: spelling-app
    env: python
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      
      # Build frontend with explicit path
      cd frontend && \
      npm install --legacy-peer-deps && \
      REACT_APP_API_URL=/api npm run build && \
      
      # Debug build output
      echo "Build directory contents:" && \
      ls -la build/ && \
      
      # Ensure build directory exists and copy files
      mkdir -p ../frontend/build && \
      cp -r build/* ../frontend/build/ && \
      cd ..
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 18.0.0
      - key: FLASK_DEBUG
        value: "0"
      - key: PORT
        value: "8000"  # Changed to port 8000
      - key: REACT_APP_API_URL
        value: "/api"
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /*
        destination: /index.html