services:
  - type: web
    name: spelling-app
    env: python
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      # Install and build frontend
      cd frontend && \
      npm install --legacy-peer-deps && \
      REACT_APP_API_URL=/api npm run build && \
      cd ..
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT --workers 4 --access-logfile - --error-logfile - --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 18.0.0
      - key: FLASK_DEBUG
        value: "0"
    staticPublishPath: ./frontend/build
    healthCheckPath: /api/health