services:
  - type: web
    name: spelling-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build && cd ..
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /api/health 