services:
  - type: web
    name: spelling-app
    env: python
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      # Build frontend with explicit path
      cd frontend && \
      npm install --legacy-peer-deps && \
      REACT_APP_API_URL=/api npm run build && \
      cd .. && \
      # Verify build directory exists
      mkdir -p frontend/build && \
      ls -la frontend/build
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 18.0.0
      - key: FLASK_DEBUG
        value: "0"
      - key: PORT
        value: "10000"
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /*
        destination: /index.html