services:
  - type: web
    name: spelling-app
    env: python
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      
      # Debug current location
      echo "Current directory:" && pwd
      
      # Build frontend
      cd frontend && \
      npm install --legacy-peer-deps && \
      REACT_APP_API_URL=/api npm run build && \
      
      # Debug build directory
      echo "Build directory contents:" && \
      ls -la build/ && \
      
      # Create target directory and copy files
      mkdir -p /opt/render/project/src/frontend/build && \
      cp -r build/* /opt/render/project/src/frontend/build/ && \
      
      # Verify copy
      echo "Verifying copied files:" && \
      ls -la /opt/render/project/src/frontend/build/ && \
      cd ..
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 18.0.0
      - key: FLASK_DEBUG
        value: "0"
      - key: PORT
        value: "8000"
      - key: REACT_APP_API_URL
        value: "/api"
    staticPublishPath: /opt/render/project/src/frontend/build
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /*
        destination: /index.html